name: Imagen Docker

on:
  push:
    paths:
      - "Dockerfile"
      - "package.json"
      - "bun.lockb"

jobs:
  build:
    runs-on: debian-12-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: spmanolo/calidad-aire:latest
